version: '3.8'

services:  
  crypto:
    build:
      context: ../crypto-app
      dockerfile: ../dev-config/Dockerfile.prod
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks: 
      - crypto-app
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST: ${DATABASE_NAME}
      POSTGRES_CLIENT: ${DATABASE_CLIENT}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - crypto-app

networks:
  crypto-app:
volumes:
  db: